### ISSUE TITLE
Test uploaded files' format

### ISSUE THREAD

**Issue by tanakaworld** [tanakaworld/graphql-upload-sample#1]

**Comment by tanakaworld** [comment]
## express-graphql

- [branch](https://github.com/tanakaworld/graphql-upload-sample/tree/express-graphql)
- `docs` is an array of objects
- `doc.file` is a promise

### single file

![image](https://user-images.githubusercontent.com/3489430/229205409-297d4cc5-657f-460e-b267-b27c428a7cef.png)

### multiple files

![image](https://user-images.githubusercontent.com/3489430/229205496-e9902159-15b9-4020-a915-dc7e5c5233c3.png)

**Comment by tanakaworld** [comment]
## Apollo Server

- [branch](https://github.com/tanakaworld/graphql-upload-sample/tree/apollo-server)
- `docs` is an array of objects
- `doc.file` is a promise

### single file

![image](https://user-images.githubusercontent.com/3489430/229205736-9ffd2b62-29c3-4684-9cb8-6d747026f62e.png)


### multiple files

![image](https://user-images.githubusercontent.com/3489430/229205832-8f8df410-1ea9-4a9a-8f03-ddebf5e01560.png)

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
maodoutech, @coreyphillips, @forecho, @atiselsts, @zivhacker, @cnn007, @mark1yo, @imorte, @davidteather, @DIMCHERRY, @AlexPereverzyev, @ariverox, @dsclearuc, @darwindu, @f4try, @bernielxy, @divefox, @TRINITRONIC, @bishalbar77, @itsnotvalid, @red-butterfly, @howtodobetter, @tcclks, @johnMana, @joshmarlow, @feelingit, @0xCFx, @sonph, @MrPops, @Nua07, @ClaudGross, @chi11ed, @curlhash, @eraserhero, @dimlucas, @deepchhatralia, @gzg55, @ayurich, @Thammada, @fhsi5794, @vasspilka, @ohardt-cash, @adventure-zeros, @usametov, @stone100, @ongkjh, @kiok46, @TonyPythoneer, @zouguangxian, @qocu
